////********** AUTOGENERATED FILE: DO NOT REMOVE ANY COMMENT IN THIS STYLE **********////
////********** START IMPORTS **********////
import 'package:injectable/injectable.dart';
import 'package:taousapp/notifications/domain/data/notifications_remote_datasource.dart';
import 'package:taousapp/notifications/domain/repository/notifications_repository.dart';
import 'package:taousapp/notifications/domain/usecases/get_notifications.dart';
import 'package:taousapp/notifications/domain/usecases/get_unread_notifications_count.dart';
import 'package:taousapp/notifications/domain/usecases/update_fcm_token.dart';
////********** END IMPORTS **********////

@LazySingleton(as: NotificationsRepository)
class NotificationsRepositoryImp implements NotificationsRepository {
////********** END VARIABLES **********////

  NotificationsRepositoryImp({
////********** START RECEIVE VALUES **********////
    required NotificationsRemoteDataSource firebaseMessagingRemoteDataSource,
////********** END RECEIVE VALUES **********////
  }) :
////********** START SET VALUES **********////
        _firebaseMessagingRemoteDataSource = firebaseMessagingRemoteDataSource
////********** END SET VALUES **********////
  ;

////********** START VARIABLES **********////
  final NotificationsRemoteDataSource _firebaseMessagingRemoteDataSource;

////********** START METHODS **********////
  /// [UpdateFcmTokenUsecaseInput] is received to [updateFcmToken] method
  /// as parameter
  /// [UpdateFcmTokenUsecaseOutput] is returned from [updateFcmToken] method
  @override
  Future<UpdateFcmTokenUsecaseOutput> updateFcmToken(
    UpdateFcmTokenUsecaseInput input,
  ) async {
    return _firebaseMessagingRemoteDataSource.updateFcmToken(input);
  }

  @override
  Future<GetNotificationsUsecaseOutput> getNotifications(
    GetNotificationsUsecaseInput input,
  ) async {
    return _firebaseMessagingRemoteDataSource.getNotifications(input);
  }

  @override
  Future<GetUnreadNotificationsCountUsecaseOutput> getUnreadNotificationsCount(
      GetUnreadNotificationsCountUsecaseInput input) {
    return _firebaseMessagingRemoteDataSource
        .getUnreadNotificationsCount(input);
  }

////********** END METHODS **********////
}
