import 'package:taousapp/presentation/chat_screen/domain/usecases/create_message.dart';

////********** AUTOGENERATED FILE: DO NOT REMOVE ANY COMMENT IN THIS STYLE **********////
////********** START IMPORTS **********////
////********** END IMPORTS **********////

abstract class ChatFirebaseDataSource {
  ////********** START METHODS **********////

  /// [CreateMessageUsecaseInput] is received to [createMessage] method as
  /// parameter
  /// [CreateMessageUsecaseOutput] is returned from [createMessage] method
  Future<CreateMessageUsecaseOutput> createMessage(
    CreateMessageUsecaseInput input,
  );

////********** END METHODS **********////
}
