name: taousapp
description: TaousApp
version: 1.0.0+1
environment:
  sdk: '>=3.1.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  connectivity_plus: ^5.0.2
  shared_preferences: ^2.2.2
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.9
  outline_gradient_button: ^2.0.1+1
  flutter_svg_provider: ^1.0.7
  grouped_list: ^5.1.2
  dotted_border: ^2.1.0
  intl: ^0.19.0
  firebase_core: ^2.24.2
  country_codes: ^2.2.0
  carousel_slider: ^4.2.1
  cloud_firestore: ^4.14.0
  firebase_auth: ^4.16.0
  loading_animation_widget: ^1.2.0+4
  firebase_messaging: ^14.7.10
  overlay_support: ^2.1.0
  flutter_local_notifications: ^16.3.0
  flutter_launcher_icons: ^0.13.1
  timeago: ^3.2.2
  firebase_storage: ^11.6.0
  shimmer: ^3.0.0
  dropdown_search: ^5.0.6
  image_picker: ^1.0.6
  permission_handler: ^11.1.0
  line_icons: ^2.0.3
  cupertino_icons: ^1.0.6


  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

  #DI
  get_it: ^7.6.6
  injectable: ^2.3.2

  # river-pod
  flutter_riverpod: ^2.4.9

  # emoji_picker_flutter
  emoji_picker_flutter: ^1.6.3

  fluttertoast: ^8.2.4




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  intl_phone_field: ^3.2.0
  build_runner: ^2.4.7

  freezed: ^2.4.6
  injectable_generator: ^2.4.1
  json_serializable: ^6.7.1


flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
  fonts: 
    - family: Nunito Sans
      fonts: 
        - asset: assets/fonts/NunitoSansRegular.ttf
          weight: 400
        - asset: assets/fonts/NunitoSansBold.ttf
          weight: 700
        - asset: assets/fonts/NunitoSansSemiBold.ttf
          weight: 600
        - asset: assets/fonts/NunitoSansLight.ttf
          weight: 300
    - family: Plus Jakarta Sans
      fonts: 
        - asset: assets/fonts/PlusJakartaSansSemiBold.ttf
          weight: 600
        - asset: assets/fonts/PlusJakartaSansBold.ttf
          weight: 700
        - asset: assets/fonts/PlusJakartaSansMedium.ttf
          weight: 500
