import 'package:taousapp/infrastructure/datasource.dart';
import 'package:taousapp/notifications/domain/usecases/get_notifications.dart';
import 'package:taousapp/notifications/domain/usecases/get_unread_notifications_count.dart';
import 'package:taousapp/notifications/domain/usecases/update_fcm_token.dart';

////********** AUTOGENERATED FILE: DO NOT REMOVE ANY COMMENT IN THIS STYLE **********////
////********** START IMPORTS **********////

////********** END IMPORTS **********////

abstract class NotificationsRemoteDataSource extends DataSource {
  ////********** START METHODS **********////
  /// [UpdateFcmTokenUsecaseInput] is received to [updateFcmToken] method as
  /// parameter
  /// [UpdateFcmTokenUsecaseOutput] is returned from [updateFcmToken] method
  Future<UpdateFcmTokenUsecaseOutput> updateFcmToken(
    UpdateFcmTokenUsecaseInput input,
  );

  /// [GetNotificationsUsecaseInput] is received to [updateFcmToken] method as
  /// parameter
  /// [GetNotificationsUsecaseOutput] is returned from [updateFcmToken] method
  Future<GetNotificationsUsecaseOutput> getNotifications(
    GetNotificationsUsecaseInput input,
  );

  /// [GetNotificationsUsecaseInput] is received
  /// to [getUnreadNotificationsCount] method as
  /// parameter
  /// [GetNotificationsUsecaseOutput] is returned
  /// from [getUnreadNotificationsCount] method
  Future<GetUnreadNotificationsCountUsecaseOutput> getUnreadNotificationsCount(
    GetUnreadNotificationsCountUsecaseInput input,
  );

////********** END METHODS **********////
}
