////********** AUTOGENERATED FILE: DO NOT REMOVE ANY COMMENT IN THIS STYLE **********////
////********** START IMPORTS **********////
import 'package:injectable/injectable.dart';
import 'package:taousapp/core/utils/logger.dart';
import 'package:taousapp/notifications/domain/data/notifications_remote_datasource.dart';
import 'package:taousapp/notifications/domain/usecases/get_notifications.dart';
import 'package:taousapp/notifications/domain/usecases/update_fcm_token.dart';
////********** END IMPORTS **********////

@LazySingleton(as: NotificationsRemoteDataSource)
class NotificationsRemoteDataSourceImp
    implements NotificationsRemoteDataSource {
  NotificationsRemoteDataSourceImp({
    required Logger logger,
  }) : _logger = logger;
  final Logger _logger;

////********** START METHODS **********////
  @override
  Future<UpdateFcmTokenUsecaseOutput> updateFcmToken(
    UpdateFcmTokenUsecaseInput input,
  ) async {
    return UpdateFcmTokenUsecaseOutput();
  }

  @override
  Future<GetNotificationsUsecaseOutput> getNotifications(
    GetNotificationsUsecaseInput input,
  ) async {
    return GetNotificationsUsecaseOutput(notifications: []);
  }

////********** END METHODS **********////
}
