////********** AUTOGENERATED FILE: DO NOT REMOVE ANY COMMENT IN THIS STYLE **********////
////********** START IMPORTS **********////
import 'package:injectable/injectable.dart';
import 'package:taousapp/infrastructure/repository.dart';
import 'package:taousapp/presentation/chat_screen/data/source/chat_firebase_datasource.dart';
import 'package:taousapp/presentation/chat_screen/domain/repository/chat_repository.dart';
import 'package:taousapp/presentation/chat_screen/domain/usecases/create_chat.dart';
import 'package:taousapp/presentation/chat_screen/domain/usecases/create_message.dart';
import 'package:taousapp/presentation/chat_screen/domain/usecases/delete_chat.dart';
import 'package:taousapp/presentation/chat_screen/domain/usecases/delete_message.dart';
import 'package:taousapp/presentation/chat_screen/domain/usecases/get_all_chats.dart';
import 'package:taousapp/presentation/chat_screen/domain/usecases/get_all_messages.dart';
import 'package:taousapp/presentation/chat_screen/domain/usecases/get_chat_id_for_users.dart';
import 'package:taousapp/presentation/chat_screen/domain/usecases/update_unread_messages_usecase.dart';
////********** END IMPORTS **********////

abstract class ChatRepository extends Repository {
////********** START METHODS **********////
  /// [CreateChatUsecaseInput] is received to [createChat] method as parameter
  /// [CreateChatUsecaseOutput] is returned from [createChat] method
  Future<CreateChatUsecaseOutput> createChat(CreateChatUsecaseInput input);

  /// [DeleteChatUsecaseInput] is received to [deleteChat] method as parameter
  /// [DeleteChatUsecaseOutput] is returned from [deleteChat] method
  Future<DeleteChatUsecaseOutput> deleteChat(DeleteChatUsecaseInput input);

  /// [CreateMessageUsecaseInput] is received to [createMessage] method as
  /// parameter
  /// [CreateMessageUsecaseOutput] is returned from [createMessage] method
  Future<CreateMessageUsecaseOutput> createMessage(
    CreateMessageUsecaseInput input,
  );

  /// [DeleteMessageUsecaseInput] is received to [deleteMessage] method as
  /// parameter
  /// [DeleteMessageUsecaseOutput] is returned from [deleteMessage] method
  Future<DeleteMessageUsecaseOutput> deleteMessage(
    DeleteMessageUsecaseInput input,
  );

  /// [GetAllChatsUsecaseInput] is received to [getAllChats] method as
  /// parameter
  /// [GetAllChatsUsecaseOutput] is returned from [getAllChats] method
  Future<GetAllChatsUsecaseOutput> getAllChats(GetAllChatsUsecaseInput input);

  /// [GetAllMessagesUsecaseInput] is received to [getAllMessages] method as
  /// parameter
  /// [GetAllMessagesUsecaseOutput] is returned from [getAllMessages] method
  Future<GetAllMessagesUsecaseOutput> getAllMessages(
    GetAllMessagesUsecaseInput input,
  );

  /// [GetChatIdForUsersUsecaseInput] is received to [getChatIdForUsers] method
  /// as parameter
  /// [GetChatIdForUsersUsecaseOutput] is returned from [getChatIdForUsers]
  /// method
  Future<GetChatIdForUsersUsecaseOutput> getChatIdForUsers(
    GetChatIdForUsersUsecaseInput input,
  );

  /// [MarkReadMessagesUsecaseInput] is received to [updateUnReadMessages]
  /// method as parameter
  /// [MarkReadMessagesUsecaseOutput] is returned from [updateUnReadMessages]
  /// method
  Future<MarkReadMessagesUsecaseOutput> updateUnReadMessages(
    MarkReadMessagesUsecaseInput input,
  );

////********** END METHODS **********////
}
